# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpha-nvim = {
    pname = "alpha-nvim";
    version = "41283fb402713fc8b327e60907f74e46166f4cfd";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "41283fb402713fc8b327e60907f74e46166f4cfd";
      fetchSubmodules = false;
      sha256 = "sha256-kTVPKZ/e1us/uHfSwFwR38lFYN8EotJq2jKz6xm/eqg=";
    };
    date = "2024-02-25";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "31fcfb02c47952d5c75aec893b93b2878abe5fbb";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "31fcfb02c47952d5c75aec893b93b2878abe5fbb";
      fetchSubmodules = false;
      sha256 = "sha256-4hh1WXWJ2RdycyHXnXaYu4348JCtROlwPym0cAAdCFk=";
    };
    date = "2024-06-28";
  };
  cmp-buffer = {
    pname = "cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  cmp-cmdline = {
    pname = "cmp-cmdline";
    version = "d250c63aa13ead745e3a40f61fdd3470efde3923";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "d250c63aa13ead745e3a40f61fdd3470efde3923";
      fetchSubmodules = false;
      sha256 = "sha256-iBmXp+gUSMbgfkv7c7RDQAwPq02e07wEnBETP0dWBOo=";
    };
    date = "2024-03-22";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
      fetchSubmodules = false;
      sha256 = "sha256-CT1+Z4XJBVsl/RqvJeGmyitD6x7So0ylXvvef5jh7I8=";
    };
    date = "2024-05-17";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  cmp_luasnip = {
    pname = "cmp_luasnip";
    version = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
    src = fetchFromGitHub {
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
      fetchSubmodules = false;
      sha256 = "sha256-nUJJl2zyK/oSwz5RzI9j3gf9zpDfCImCYbPbVsyXgz8=";
    };
    date = "2023-10-09";
  };
  crates = {
    pname = "crates";
    version = "c3fd47391de6999f4c939af89494d08443f71916";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "c3fd47391de6999f4c939af89494d08443f71916";
      fetchSubmodules = false;
      sha256 = "sha256-y1NLR4w7kGVJO5gGSguQB5BpDYrUgyPz/4Tf01c9hG8=";
    };
    date = "2024-07-01";
  };
  editorconfig = {
    pname = "editorconfig";
    version = "5b9e303e1d6f7abfe616ce4cc8d3fffc554790bf";
    src = fetchFromGitHub {
      owner = "gpanders";
      repo = "editorconfig.nvim";
      rev = "5b9e303e1d6f7abfe616ce4cc8d3fffc554790bf";
      fetchSubmodules = false;
      sha256 = "sha256-pR57tITdVGF4luEmmRYv/XFb35E3KDfcgYRijkPAc+Y=";
    };
    date = "2023-01-10";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  harpoon = {
    pname = "harpoon";
    version = "0378a6c428a0bed6a2781d459d7943843f374bce";
    src = fetchFromGitHub {
      owner = "ThePrimeagen";
      repo = "harpoon";
      rev = "0378a6c428a0bed6a2781d459d7943843f374bce";
      fetchSubmodules = false;
      sha256 = "sha256-FZQH38E02HuRPIPAog/nWM55FuBxKp8AyrEldFkoLYk=";
    };
    date = "2024-04-09";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "65e20ab94a26d0e14acac5049b8641336819dfc7";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "65e20ab94a26d0e14acac5049b8641336819dfc7";
      fetchSubmodules = false;
      sha256 = "sha256-PSsXBB2KOFPJJ1O8fpTvsVe2A0/wU6Ae9dN/UemraZM=";
    };
    date = "2024-06-28";
  };
  lazy = {
    pname = "lazy";
    version = "a1d23e80badccc407d6b289d1c366ff2888812b6";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "a1d23e80badccc407d6b289d1c366ff2888812b6";
      fetchSubmodules = false;
      sha256 = "sha256-KhCDEbpHnNFr4IUKjQPLp+kbV71ynvQMZ82cCSwYvd0=";
    };
    date = "2024-07-05";
  };
  lazydev-nvim = {
    pname = "lazydev-nvim";
    version = "9876fde06f7fc07dca4fe386b0ecfd0d9fa97f6f";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "9876fde06f7fc07dca4fe386b0ecfd0d9fa97f6f";
      fetchSubmodules = false;
      sha256 = "sha256-sKO/FABEZRW1o7TDhS03yTcD85O0SjmHgJV2qxZCfQw=";
    };
    date = "2024-07-04";
  };
  lazygit = {
    pname = "lazygit";
    version = "ad3e1ea592f9d13e86e0d4e850224d9d78069508";
    src = fetchFromGitHub {
      owner = "kdheepak";
      repo = "lazygit.nvim";
      rev = "ad3e1ea592f9d13e86e0d4e850224d9d78069508";
      fetchSubmodules = false;
      sha256 = "sha256-/fAsPz+6+OzT5WVqWmLf+mrN/xE6AtM4IHNJTHWr+aY=";
    };
    date = "2024-05-12";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "1735dd5a5054c1fb7feaf8e8658dbab925f4f0cf";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "1735dd5a5054c1fb7feaf8e8658dbab925f4f0cf";
      fetchSubmodules = false;
      sha256 = "sha256-/QLdBU/Zwmkw1NGuLBD48tvrmIP9d9WHhgcLEQgRTWo=";
    };
    date = "2024-01-11";
  };
  ltex-extra = {
    pname = "ltex-extra";
    version = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
    src = fetchFromGitHub {
      owner = "barreiroleo";
      repo = "ltex-extra.nvim";
      rev = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
      fetchSubmodules = false;
      sha256 = "sha256-OGeeEIF+z03DdJO2d2kzQ0lZnIYLabp6irYPqYgbCbc=";
    };
    date = "2024-06-15";
  };
  lualine = {
    pname = "lualine";
    version = "0a5a66803c7407767b799067986b4dc3036e1983";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "0a5a66803c7407767b799067986b4dc3036e1983";
      fetchSubmodules = false;
      sha256 = "sha256-WcH2dWdRDgMkwBQhcgT+Z/ArMdm+VbRhmQftx4t2kNI=";
    };
    date = "2024-04-05";
  };
  luasnip = {
    pname = "luasnip";
    version = "ce0a05ab4e2839e1c48d072c5236cce846a387bc";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "ce0a05ab4e2839e1c48d072c5236cce846a387bc";
      fetchSubmodules = false;
      sha256 = "sha256-zjefbPMiKxwYsBzE75jQRVNFMDSnCq1hKe1cBBqMRWg=";
    };
    date = "2024-06-28";
  };
  neo-tree-nvim = {
    pname = "neo-tree-nvim";
    version = "206241e451c12f78969ff5ae53af45616ffc9b72";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "206241e451c12f78969ff5ae53af45616ffc9b72";
      fetchSubmodules = false;
      sha256 = "sha256-eNGuQEjAKsPuRDGaw95kCVOmP64ZDnUuFBppqtcrhZ4=";
    };
    date = "2024-06-11";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "dd0f5ebb06431505a6de75fd1bc50cd62226adef";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "dd0f5ebb06431505a6de75fd1bc50cd62226adef";
      fetchSubmodules = false;
      sha256 = "sha256-EGz5yqeyhn8B3oWgOuuvuEaRP9zOJQsKeQmzkodcE6A=";
    };
    date = "2024-06-30";
  };
  none-ls = {
    pname = "none-ls";
    version = "0d1b3fa2ad0b371b94cb4b9a27ba6e5a1a915c91";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "0d1b3fa2ad0b371b94cb4b9a27ba6e5a1a915c91";
      fetchSubmodules = false;
      sha256 = "sha256-CV8igAMAvPitl7+CWFWZ58l7nQiqtglVoEvqpy7v5SQ=";
    };
    date = "2024-06-28";
  };
  nui = {
    pname = "nui";
    version = "61574ce6e60c815b0a0c4b5655b8486ba58089a1";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "61574ce6e60c815b0a0c4b5655b8486ba58089a1";
      fetchSubmodules = false;
      sha256 = "sha256-o2iNktcWxL0oCtCkbARMiWnTlZA8QWQHy2qeOanBlO4=";
    };
    date = "2024-06-26";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "a110e12d0b58eefcf5b771f533fc2cf3050680ac";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "a110e12d0b58eefcf5b771f533fc2cf3050680ac";
      fetchSubmodules = false;
      sha256 = "sha256-7tEfEjWH5pneI10jLYpenoysRQPa2zPGLTNcbMX3x2I=";
    };
    date = "2024-06-08";
  };
  nvim-colorizer-lua = {
    pname = "nvim-colorizer-lua";
    version = "85855b38011114929f4058efc97af1059ab3e41d";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "85855b38011114929f4058efc97af1059ab3e41d";
      fetchSubmodules = false;
      sha256 = "sha256-oKvFN2K+ASlPNwj2rhptR/ErYgo6XKBPhXSZotDdCP0=";
    };
    date = "2023-12-23";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "cf97d2485fc3f6d4df1b79a3ea183e24c272215e";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "cf97d2485fc3f6d4df1b79a3ea183e24c272215e";
      fetchSubmodules = false;
      sha256 = "sha256-Ms3GgwbzOU22hwqE2TgmccZzsXvoE4xYuCioAxRnRu8=";
    };
    date = "2024-07-03";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "8649f694d3e76ee10c19255dece6411c29206a54";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "8649f694d3e76ee10c19255dece6411c29206a54";
      fetchSubmodules = false;
      sha256 = "sha256-0p5n/V8Jlj9XyxV/fuMwsbQ7oV5m9H2GqZZEA/njxCQ=";
    };
    date = "2023-11-30";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "d333b6f167900f6d9d42a59005d82919830626bf";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "d333b6f167900f6d9d42a59005d82919830626bf";
      fetchSubmodules = false;
      sha256 = "sha256-wxyHwL/uFdp6w32CVHgSOWkzRrIRuFvWh+J2401RAAA=";
    };
    date = "2024-05-17";
  };
  nvim-tree-lua = {
    pname = "nvim-tree-lua";
    version = "8b2c5c678be4b49dff6a2df794877000113fd77b";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "8b2c5c678be4b49dff6a2df794877000113fd77b";
      fetchSubmodules = false;
      sha256 = "sha256-RfrbxYD7RYBEy/grSYnKKkWd4BHxGYEFeLiDB5OYGpg=";
    };
    date = "2024-06-23";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "74dc34a7fa8e1ea4bcc4578f7a4b14e3ec8c189f";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "74dc34a7fa8e1ea4bcc4578f7a4b14e3ec8c189f";
      fetchSubmodules = false;
      sha256 = "sha256-SP80EbYxGYKP5HLIH1rIzdJoVMgVei5hJrp4C0XCfmA=";
    };
    date = "2024-07-05";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "c0cfc1738361b5da1cd0a962dd6f774cc444f856";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "c0cfc1738361b5da1cd0a962dd6f774cc444f856";
      fetchSubmodules = false;
      sha256 = "sha256-j/B/E1VltJ/QpVFtDKAdVC4+KZ5Mz8dQP5kd8HIHjLs=";
    };
    date = "2024-06-09";
  };
  plenary = {
    pname = "plenary";
    version = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
      fetchSubmodules = false;
      sha256 = "sha256-5Jf2mWFVDofXBcXLbMa417mqlEPWLA+cQIZH/vNEV1g=";
    };
    date = "2024-05-20";
  };
  presence = {
    pname = "presence";
    version = "87c857a56b7703f976d3a5ef15967d80508df6e6";
    src = fetchFromGitHub {
      owner = "andweeb";
      repo = "presence.nvim";
      rev = "87c857a56b7703f976d3a5ef15967d80508df6e6";
      fetchSubmodules = false;
      sha256 = "sha256-ZpsunLsn//zYgUtmAm5FqKVueVd/Pa1r55ZDqxCimBk=";
    };
    date = "2023-01-29";
  };
  py_lsp = {
    pname = "py_lsp";
    version = "278db39aedd697613851861b5ea8b0d9138fc06f";
    src = fetchFromGitHub {
      owner = "hallerpatrick";
      repo = "py_lsp.nvim";
      rev = "278db39aedd697613851861b5ea8b0d9138fc06f";
      fetchSubmodules = false;
      sha256 = "sha256-cNvh7A091kdeLoaoz2ysWuNV0BqzTXgjntU/pDZS92U=";
    };
    date = "2024-02-15";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "5c9660801ce345cd3835e1947c12b54290ab7e71";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "5c9660801ce345cd3835e1947c12b54290ab7e71";
      fetchSubmodules = false;
      sha256 = "sha256-8NnGg6Gn0mjOC42Z1GhHMAUTPI6exednMKQRoFIY0o4=";
    };
    date = "2024-06-14";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "af4de6a35d128ce71c75a9a7846bf089aea76f50";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "af4de6a35d128ce71c75a9a7846bf089aea76f50";
      fetchSubmodules = false;
      sha256 = "sha256-W8cSTcF+xapvpBUZYccwkPmkNkdK3wlbzC5rpbv6HZI=";
    };
    date = "2024-06-29";
  };
  schemastore = {
    pname = "schemastore";
    version = "30946db59edba23103c2f524e636910a7a2160df";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "30946db59edba23103c2f524e636910a7a2160df";
      fetchSubmodules = false;
      sha256 = "sha256-bOSE++BUWuocEg7f0uYtGZZVvR4SM7ZOOz7yR7DegGQ=";
    };
    date = "2024-07-04";
  };
  telescope = {
    pname = "telescope";
    version = "bfcc7d5c6f12209139f175e6123a7b7de6d9c18a";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "bfcc7d5c6f12209139f175e6123a7b7de6d9c18a";
      fetchSubmodules = false;
      sha256 = "sha256-U6fgii9FlJy+bHAtYVnZEOyiUAqlBHTvMFc4mo+xS/s=";
    };
    date = "2024-07-01";
  };
  telescope-file-browser = {
    pname = "telescope-file-browser";
    version = "a7ab9a957b17199183388c6f357d614fcaa508e5";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "a7ab9a957b17199183388c6f357d614fcaa508e5";
      fetchSubmodules = false;
      sha256 = "sha256-2ZXjp0Kzr2Xp7/BjiWBUi2lq6uS80Ada/pXLqxeBfDw=";
    };
    date = "2024-06-09";
  };
  telescope-ui-select = {
    pname = "telescope-ui-select";
    version = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-ui-select.nvim";
      rev = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
      fetchSubmodules = false;
      sha256 = "sha256-YRhNmmG4gx9Ht8JwjQfbTjJyTHEuZmtP6lqnhOsk8bE=";
    };
    date = "2023-12-04";
  };
  tiny-devicons-auto-colors-nvim = {
    pname = "tiny-devicons-auto-colors-nvim";
    version = "9be4af5b1bc1f26a11206ed7ce8bf44312e7941a";
    src = fetchFromGitHub {
      owner = "rachartier";
      repo = "tiny-devicons-auto-colors.nvim";
      rev = "9be4af5b1bc1f26a11206ed7ce8bf44312e7941a";
      fetchSubmodules = false;
      sha256 = "sha256-JGI9y5Y0AocTO2M1Lt28UxVP0rZv20ZHJw0wKurJsh8=";
    };
    date = "2024-06-16";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "51e10f838e84b4756c16311d0b1ef0972c6482d2";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "51e10f838e84b4756c16311d0b1ef0972c6482d2";
      fetchSubmodules = false;
      sha256 = "sha256-CcQjhccjUG5mEsPaNRR/doYKHw+HiVT/nhbk1kT5axo=";
    };
    date = "2024-06-12";
  };
  trouble = {
    pname = "trouble";
    version = "026e420bf9878ee97133f8fbf906261f3249b17a";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "026e420bf9878ee97133f8fbf906261f3249b17a";
      fetchSubmodules = false;
      sha256 = "sha256-kYKlYO5obF+vO6rD8Ug2b0bBFTqnLVhvVFTxhJBoSrM=";
    };
    date = "2024-07-04";
  };
  typescript-tools = {
    pname = "typescript-tools";
    version = "5da4d695d66f676eb6ea766b946e86f93baaafe7";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "5da4d695d66f676eb6ea766b946e86f93baaafe7";
      fetchSubmodules = false;
      sha256 = "sha256-UzYqDgtb0+eI+LHYX/RqCkckqaft5EOzD35257ZOc10=";
    };
    date = "2024-06-30";
  };
  undotree = {
    pname = "undotree";
    version = "56c684a805fe948936cda0d1b19505b84ad7e065";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "56c684a805fe948936cda0d1b19505b84ad7e065";
      fetchSubmodules = false;
      sha256 = "sha256-UIroW89ALMRdxSkNGU2VPeuXJxR+25wJ+AakRcjwx/s=";
    };
    date = "2024-04-16";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "d0c1a437536778bcc8174b7cb2ffdf98f611e6fe";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "d0c1a437536778bcc8174b7cb2ffdf98f611e6fe";
      fetchSubmodules = false;
      sha256 = "sha256-v0M1dzLMNyBsd+73dX5bk99AJNh4nRmCikhlb+Xpazw=";
    };
    date = "2024-06-25";
  };
}
